CREATE TABLE "JBPCC_USERS"
(
   ID INTEGER PRIMARY KEY not null,
   LOGINNAME VARCHAR(30) not null,
   FORENAME VARCHAR(30),
   SURNAME VARCHAR(30),
   ENABLED VARCHAR(1) not null,
   PASSWORD VARCHAR(1000)
);

CREATE TABLE "JBPCC_SERVERS"
(
   ID INTEGER PRIMARY KEY not null,
   NAME VARCHAR(150) not null,
   PORT INTEGER not null,
   USERNAME VARCHAR(150),
   IP VARCHAR(20) not null,
   PASSWORD VARCHAR(100),
   JMXAGENTNAME VARCHAR(100) not null
);

CREATE TABLE "JBPCC_USERSERVERS"
(
   USERID INTEGER not null,
   SERVERID INTEGER not null,
   PRIMARY KEY (USERID, SERVERID),
   FOREIGN KEY (USERID) references JBPCC_USERS(ID),
   FOREIGN KEY (SERVERID) references JBPCC_SERVERS(ID)
);


INSERT INTO JBPCC_USERS(ID, LOGINNAME, FORENAME, SURNAME, ENABLED, PASSWORD) 
VALUES (1, 'admin', 'JBPCC', 'Administrator', 'Y', 'admin');

