CREATE TABLE "USERS"
(
   ID INTEGER PRIMARY KEY not null,
   LOGINNAME VARCHAR(30) not null,
   FORENAME VARCHAR(30),
   SURNAME VARCHAR(30),
   ENABLED VARCHAR(1) not null,
   PASSWORD VARCHAR(1000)
);

CREATE TABLE "SERVERS"
(
   ID INTEGER PRIMARY KEY not null,
   NAME VARCHAR(150) not null,
   PORT INTEGER not null,
   USERNAME VARCHAR(150),
   IP VARCHAR(20) not null,
   PASSWORD VARCHAR(100),
   JMXAGENTNAME VARCHAR(100) not null
);

CREATE TABLE "USERSERVERS"
(
   USERID INTEGER not null,
   SERVERID INTEGER not null,
   PRIMARY KEY (USERID, SERVERID)
);

ALTER TABLE USERSERVERS
ADD CONSTRAINT FK_USESER_USEID
FOREIGN KEY (USERID)
REFERENCES USERS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USERSERVERS
ADD CONSTRAINT FK_USESER_SERID
FOREIGN KEY (SERVERID)
REFERENCES SERVERS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


INSERT INTO USERS(ID, LOGINNAME, FORENAME, SURNAME, ENABLED, PASSWORD) 
VALUES (1, 'admin', 'JBPCC', 'Administrator', 'Y', 'admin'); 

commit;



